language: cpp
sudo: required
dist: bionic
cache:
  directories:
  - "${HOME}/.conan"
  - "${TRAVIS_BUILD_DIR}/cmake"
  - "${TRAVIS_BUILD_DIR}/arrayfire"
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler:
    - gcc
    git:
      submodules: false
    before_install:
    - git submodule update --init
    - source .CI/travis/install_linux.sh
    - source .CI/travis/install-arrayfire_linux.sh
    - source .CI/travis/install-cmake_linux.sh
    script:
    - source .CI/travis/build_linux.sh
  - os: linux
    dist: bionic
    sudo: required
    compiler:
    - clang
    git:
      submodules: false
    before_install:
    - git submodule update --init
    - source .CI/travis/install_linux.sh
    - source .CI/travis/install-arrayfire_linux.sh
    - source .CI/travis/install-cmake_linux.sh
    script:
    - source .CI/travis/build_linux.sh
    before_deploy:
    - cpack
    - cpack -G DEB
    - cpack -G RPM
    - mv khiva.sh khiva-${TRAVIS_TAG}.sh
    deploy:
      name: "${TRAVIS_TAG} - Linux"
      body: "${TRAVIS_COMMIT_MESSAGE}"
      skip_cleanup: true
      provider: releases
      api_key:
        secure: nq+uAF9nr8CufNHlsIxLhhADjci6fte+qXA32Dfq0A8ljWQiDsmbLY3e7+ilBoD9HoBrHElERb/UGHEjAF6DUc9JVut2PfquX9akZbLT8gF98ELodmt3AwdCCQTMm6xuxZU5P1T4RbrAYdrzvqZYCwiY84JSwGs3Wh66MzDxk+LYnFxXkVqPLQy2bwfRhN1LEhw/WoZBW2sWxJEPHxgOG/tXsWLkfY8T+tGFfu0Gw2qkS8s2HjEZXWuaEXu4CMZUzYaRAMn2utW1OtUZR++MlR7Fge4jX9Z0Q8kFAb22Zd7L6orcTyvX2w9ZPTB1NOLmjye503xsnfPS8n49+Z4EDIcgEYNzBEJlbrKr3jPoCp8I1GNsC4WSLGWMkGuqz4u6UJVHc9c9D/FHLITpaImo5pF+yUVD/PJK0ZBAFpzgMomV4kVlOLIWkbGcKcgyW6AryFs9CnT37RTTSzFNkUX5+ew81nNg3YJBjYSOGiC4KGLzpetUweMME4uxr8LGsLvW9HqOvFLSQIgIxivOwyqZmfoQiigtv+jl7+SA1cMRkg5GMohwnvkoRqnamQKYK4TYNsFpEUDmSgcZDVbDODQyUCvG6aa2/pgPtzrSBLRGzLwkUIXqaucG3UrN85i41XNltiqOpDEpTYRRpESJ3yzNLGqfDj9lfprTIWR3EgWFHUg=
        file_glob: true
      file:
      - "${TRAVIS_BUILD_DIR}/build/khiva-*.deb"
      - "${TRAVIS_BUILD_DIR}/build/khiva-*.rpm"
      - "${TRAVIS_BUILD_DIR}/build/khiva-${TRAVIS_TAG}.sh"
      draft: true
      prerelease: false
      on:
        tags: true
  - os: osx
    osx_image: xcode9.3
    compiler:
    - gcc
    env:
    - TRAVIS_PYTHON_VERSION=3.6.5
    cache:
      directories:
      - "${HOME}/.conan"
      - "${TRAVIS_BUILD_DIR}/cmake"
      - "${TRAVIS_BUILD_DIR}/arrayfire"
      - "$HOME/.pyenv"
      - "$HOME/Library/Caches/Homebrew"
    git:
      submodules: false
    before_install:
    - git submodule update --init
    - source .CI/travis/install_osx.sh
    - source .CI/travis/install-arrayfire_osx.sh
    script:
    - source .CI/travis/build_osx.sh
  - os: osx
    osx_image: xcode9.3
    compiler:
    - clang
    env:
    - TRAVIS_PYTHON_VERSION=3.6.5
    cache:
      directories:
      - "${HOME}/.conan"
      - "${TRAVIS_BUILD_DIR}/cmake"
      - "${TRAVIS_BUILD_DIR}/arrayfire"
      - "$HOME/.pyenv"
      - "$HOME/Library/Caches/Homebrew"
    git:
      submodules: false
    before_install:
    - git submodule update --init
    - source .CI/travis/install_osx.sh
    - source .CI/travis/install-arrayfire_osx.sh
    script:
    - source .CI/travis/build_osx.sh
    after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - source .CI/travis/codecov.sh
    - cd ${TRAVIS_BUILD_DIR}
    before_deploy:
    - cd build
    - cpack -G productbuild
    deploy:
      name: "${TRAVIS_TAG} - MacOS"
      body: "${TRAVIS_COMMIT_MESSAGE}"
      skip_cleanup: true
      provider: releases
      api_key:
        secure: nq+uAF9nr8CufNHlsIxLhhADjci6fte+qXA32Dfq0A8ljWQiDsmbLY3e7+ilBoD9HoBrHElERb/UGHEjAF6DUc9JVut2PfquX9akZbLT8gF98ELodmt3AwdCCQTMm6xuxZU5P1T4RbrAYdrzvqZYCwiY84JSwGs3Wh66MzDxk+LYnFxXkVqPLQy2bwfRhN1LEhw/WoZBW2sWxJEPHxgOG/tXsWLkfY8T+tGFfu0Gw2qkS8s2HjEZXWuaEXu4CMZUzYaRAMn2utW1OtUZR++MlR7Fge4jX9Z0Q8kFAb22Zd7L6orcTyvX2w9ZPTB1NOLmjye503xsnfPS8n49+Z4EDIcgEYNzBEJlbrKr3jPoCp8I1GNsC4WSLGWMkGuqz4u6UJVHc9c9D/FHLITpaImo5pF+yUVD/PJK0ZBAFpzgMomV4kVlOLIWkbGcKcgyW6AryFs9CnT37RTTSzFNkUX5+ew81nNg3YJBjYSOGiC4KGLzpetUweMME4uxr8LGsLvW9HqOvFLSQIgIxivOwyqZmfoQiigtv+jl7+SA1cMRkg5GMohwnvkoRqnamQKYK4TYNsFpEUDmSgcZDVbDODQyUCvG6aa2/pgPtzrSBLRGzLwkUIXqaucG3UrN85i41XNltiqOpDEpTYRRpESJ3yzNLGqfDj9lfprTIWR3EgWFHUg=
      file: "${TRAVIS_BUILD_DIR}/build/khiva-${TRAVIS_TAG}.pkg"
      draft: true
      prerelease: false
      on:
        tags: true